### ISSUE TITLE
How to perform space extrapolation?

### ISSUE THREAD

**Issue by skymanaditya1** [sihyun-yu/digan#11]
I trained digan on a dataset at 128x128 resolution. I now intend to generate the output at 256x256 resolution. However, when I load the pretrained model, the output img_resolution is set at 128x128. I have tried changing the output resolution at multiple places, however, I am unable to do so. Any help on this would be appreciated.

**Comment by sihyun-yu** [comment]
Hi,

have you tried and had any problems if when adjusting the coordinate range at https://github.com/sihyun-yu/digan/blob/2709d68089355e739c7d8dc2e7a016daff838d91/src/training/layers.py#L294 ?

**Comment by skymanaditya1** [comment]
I tried directly modifying the img_size parameter here and the output images generated still have a dimension of 128x128. Is there a better way of modifying this parameter?

**Comment by xyzalanix** [comment]
> Really sorry for the late reply. I was busy because of my personal stuffs. I also adjusted the resolution of torch.empty in class CoordsInput(nn.Module):
> 
> https://github.com/sihyun-yu/digan/blob/2709d68089355e739c7d8dc2e7a016daff838d91/src/training/layers.py#L85
> 
> If you still got a trouble, I can share our previous implementation (not cleaned) which includes such superresolution implementation.

Hi ! Do you mind sharing the custom scripts for the superresolution implementation?
namely `from scripts.custom_network.network_super_resol import Generator`
Thanks in advance.
