### ISSUE TITLE
Evaluation details about UCF-101 (split information)

### ISSUE THREAD

**Issue by hse1032** [sihyun-yu/digan#16]
Thanks for your great work!

I have some questions about the FVD calculation on UCF-101 dataset.

As noted in the paper, there are two different experiments for UCF-101, (train) and (train + test) split.

My questions are as below:
1. Does this codebase use (train) split? (Does this codebase uses (train) split as training data and (test) split as real statistics for FVD?)
2. When you use (train + test) split, do you also calculate the real statistics for FVD from (train + test) data?

**Comment by sihyun-yu** [comment]
Hi,

1. This codebase uses the entire (train+test) dataset.
2. Yes, I used train+test split as well for evaluation
