### ISSUE TITLE
training issuesc

### ISSUE THREAD

**Issue by Amo5** [sihyun-yu/digan#4]
Hi,
I can not download the i3d_pretrained_400.pt file
Can you provide it for me?
tanks!

**Comment by sihyun-yu** [comment]
Hi,

Can you share the error message on downloading `i3d_pretrained_400.pt`?

Sincerely,
Sihyun

**Comment by sihyun-yu** [comment]
Thank you for sharing! I think the link is somehow broken.
You can download the pertained weight here: [[link](https://drive.google.com/file/d/1fBNl3TS0LA5FEhZv5nMGJs2_7qQmvTmh/view?usp=sharing)]
