### ISSUE TITLE
dataset - ImageFolderDataset

### ISSUE THREAD

**Issue by denabazazian** [sihyun-yu/digan#7]
Thanks for sharing your great work. I found the following issues in [dataset.py](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py):

1. Path for kinetics and Sky datasets: 
Before the line [#579](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L579), there should be: 
 ```
if 'kinetics' in self._path or 'KINETICS' in self._path or 'SKY' in self._path:      
   if train:
      dir_path = os.path.join(self._path, 'train')
   else:
      dir_path = os.path.join(self._path, 'val')
 ```
and line [#579](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L579) should be changed to: 
`
self._all_fnames = {os.path.relpath(os.path.join(root, fname), start=dir_path) for root, _dirs, files in os.walk(dir_path) for fname in files}
`

Otherwise, it won't work for the data from Kinetics and Sky datasets.

2. `def _get_zipfile()` is not defined in the code, but it is used in lines [#582](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L582) and [#607](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L607). The following lines can be added after the line [#598](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L598) :
```
     def _get_zipfile(self):
         assert self._type == 'zip'
         if self._zipfile is None:
             self._zipfile = zipfile.ZipFile(self._path)
         return self._zipfile
```
3. In line [#599](https://github.com/sihyun-yu/digan/blob/master/src/training/dataset.py#L599), `def _file_ext(fname)` should be changed to  `def _file_ext(self, fname)`.

**Comment by sihyun-yu** [comment]
Thanks for sharing the issue. It seems there were several mistakes while we were refactoring the code :(
